use crate::route_table;

use super::lib::RouteDef;

pub static ROUTES: &[RouteDef] = route_table!(
  (
    "GET",
    "/settings",
    super::endpoints::settings_get_all::handle
  ),
  (
    "GET",
    "/settings/start_on_login",
    super::endpoints::settings_get_start_on_login::handle
  ),
  (
    "GET",
    "/settings/logging",
    super::endpoints::settings_get_logging::handle
  ),
  (
    "GET",
    "/settings/transcription",
    super::endpoints::settings_get_transcription::handle
  ),
  (
    "GET",
    "/settings/history",
    super::endpoints::settings_get_history::handle
  ),
  (
    "POST",
    "/settings/history/delete",
    super::endpoints::settings_delete_history_entry::handle
  ),
  (
    "GET",
    "/settings/about/logs_dir",
    super::endpoints::settings_get_about_logs_dir::handle
  ),
  (
    "POST",
    "/settings/about/open_logs_dir",
    super::endpoints::settings_open_about_logs_dir::handle
  ),
  (
    "POST",
    "/settings/about/open_external_url",
    super::endpoints::settings_open_about_external_url::handle
  ),
  (
    "POST",
    "/settings/reset/defaults",
    super::endpoints::settings_reset_defaults::handle
  ),
  (
    "POST",
    "/settings/update/start_on_login",
    super::endpoints::settings_update_start_on_login::handle
  ),
  (
    "POST",
    "/settings/update/hotkey",
    super::endpoints::settings_update_hotkey::handle
  ),
  (
    "POST",
    "/settings/update/logging",
    super::endpoints::settings_update_logging::handle
  ),
  (
    "POST",
    "/settings/update/transcription",
    super::endpoints::settings_update_transcription::handle
  ),
  (
    "POST",
    "/settings/update/history",
    super::endpoints::settings_update_history::handle
  ),
  (
    "POST",
    "/settings/window/ready",
    super::endpoints::settings_window_ready::handle
  ),
);
